- block:
  - name: Enable Virtualbox repository
    command: dnf config-manager --add-repo={{virtualbox_repository_url}}

  - name: Install Virtualbox dependencies
    dnf: name={{item}}
    with_items:
      - binutils
      - gcc
      - make
      - patch
      - libgomp
      - glibc-headers
      - glibc-devel
      - kernel-headers
      - kernel-devel
      - dkms

  - name: Install Virtualbox
    dnf: name={{item}}
    with_items:
      - VirtualBox-5.1

  - name: Rebuild kernel modules
    command: /usr/lib/virtualbox/vboxdrv.sh setup
  become: true
  tags:
    - packages
    - devel
    - software
    - restricted
    - virtualization
    - kernel
    - virtualbox
